twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_nav
        timeout: 0.5
        priority: 10
      color_avoidance:
        topic: cmd_vel_avoid
        timeout: 0.5
        priority: 20
